name: gestao_obra_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Rotas e Injeção de Dependências
  flutter_modular: ^6.3.4

  intl: ^0.19.0

  # Functional Programming
  fpdart: ^1.1.0

  # Http Client
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Notification
  onesignal_flutter: ^5.2.5

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true